version: "3"

services:
    # container for API
    api:
        build: .
        ports:
            - 9000:80
        depends_on:
            - db
        volumes:
            - ./src:/var/www/app
#            - ./deployment/configs/queue.conf:/etc/supervisor/conf.d/queue.conf
#            - ./deployment/configs/crontab.conf:/etc/crontabs/root
#            - ./deployment/configs/nginx.conf:/etc/nginx/sites-enabled/default.conf
        environment:
            - PHP_MEM_LIMIT=2048M
    db:
        image: mysql:5.7
        ports:
            - 3301:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: user123
        volumes:
            - ./src/storage/mysql:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 9022:80
        depends_on:
            - db
        environment:
            PMA_HOSTS: db
            PMA_USER: dbuser
            PMA_PASSWORD: user123
