version: "3"

services:
    # container for API
    api:
        build: .
        ports:
            - 9000:80
            - 6001:6001
        depends_on:
            - db
        volumes:
            - ./src:/var/www/app
            - ./deployment/configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini

            - ./deployment/configs/supervisor/run-echo-server.conf:/etc/supervisor/conf.d/run-echo-server.conf
            - ./deployment/configs/supervisor/redis-listen-progress.conf:/etc/supervisor/conf.d/redis-listen-progress.conf
            - ./deployment/configs/supervisor/redis-listen-tracking-process.conf:/etc/supervisor/conf.d/redis-listen-tracking-process.conf
            - ./deployment/configs/supervisor/redis-listen-clustering-process.conf:/etc/supervisor/conf.d/redis-listen-clustering-process.conf

#            - ./deployment/configs/crontab.conf:/etc/crontabs/root
            - ./deployment/configs/nginx/nginx-host.conf:/etc/nginx/sites-enabled/default.conf
            - ./deployment/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            - PHP_MEM_LIMIT=2048M
    db:
        image: mysql:5.7
        ports:
            - 3301:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: user123
        volumes:
            - ./src/storage/mysql:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 9022:80
        depends_on:
            - db
        environment:
            PMA_HOSTS: db
            PMA_USER: dbuser
            PMA_PASSWORD: user123
